executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_00.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_00.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_00.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_01.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_01.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_01.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_010.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_010.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_010.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_011.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_011.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_011.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_012.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_012.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_012.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_013.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_013.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_013.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_014.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_014.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_014.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_015.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_015.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_015.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_016.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_016.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_016.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_017.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_017.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_017.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_018.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_018.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_018.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_019.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_019.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_019.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_02.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_02.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_02.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_020.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_020.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_020.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_021.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_021.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_021.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_022.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_022.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_022.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_023.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_023.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_023.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_024.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_024.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_024.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_025.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_025.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_025.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_026.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_026.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_026.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_027.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_027.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_027.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_028.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_028.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_028.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_029.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_029.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_029.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_03.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_03.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_03.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_030.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_030.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_030.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_031.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_031.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_031.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_032.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_032.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_032.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_033.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_033.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_033.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_034.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_034.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_034.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_035.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_035.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_035.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_036.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_036.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_036.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_037.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_037.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_037.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_038.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_038.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_038.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_039.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_039.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_039.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_04.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_04.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_04.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_040.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_040.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_040.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_041.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_041.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_041.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_042.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_042.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_042.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_043.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_043.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_043.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_044.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_044.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_044.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_045.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_045.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_045.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_046.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_046.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_046.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_047.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_047.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_047.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_048.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_048.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_048.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_049.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_049.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_049.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_05.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_05.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_05.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_050.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_050.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_050.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_051.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_051.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_051.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_052.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_052.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_052.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_053.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_053.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_053.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_054.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_054.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_054.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_055.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_055.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_055.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_056.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_056.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_056.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_057.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_057.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_057.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_058.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_058.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_058.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_059.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_059.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_059.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_06.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_06.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_06.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_060.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_060.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_060.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_061.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_061.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_061.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_062.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_062.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_062.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_063.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_063.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_063.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_064.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_064.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_064.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_065.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_065.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_065.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_066.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_066.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_066.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_067.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_067.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_067.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_068.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_068.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_068.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_069.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_069.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_069.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_07.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_07.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_07.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_070.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_070.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_070.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_071.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_071.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_071.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_072.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_072.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_072.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_073.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_073.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_073.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_074.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_074.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_074.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_075.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_075.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_075.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_076.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_076.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_076.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_077.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_077.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_077.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_078.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_078.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_078.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_079.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_079.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_079.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_08.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_08.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_08.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_080.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_080.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_080.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_081.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_081.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_081.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_082.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_082.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_082.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_083.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_083.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_083.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_084.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_084.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_084.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_085.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_085.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_085.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_086.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_086.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_086.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_087.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_087.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_087.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_088.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_088.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_088.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_089.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_089.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_089.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_09.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_09.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_09.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_090.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_090.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_090.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_091.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_091.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_091.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_092.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_092.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_092.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_093.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_093.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_093.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_094.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_094.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_094.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_095.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_095.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_095.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_096.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_096.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_096.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_097.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_097.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_097.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_098.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_098.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_098.slcio
queue 1
executable              = /usr/bin/krenew                                          
notification            = never                                                           
output                  = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.out.$(cluster).$(Process)               
error                   = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.err.$(cluster).$(Process)             
log                     = /scratch1/DD4hepDetCalibration/Root_File_Generation/CondorLogs/MarlinCalib4255.log.$(cluster).$(Process)             
environment             = CONDOR_JOB=true                                                 
Universe                = vanilla                                                         
getenv                  = false                                                           
environment="KRB5CCNAME=FILE:./credentials.krb5 AKLOG=/usr/bin/aklog HOME=/afs/cern.ch/user/c/clicdpsw"                   
copy_to_spool           = true                                                            
should_transfer_files   = yes                                                             
when_to_transfer_output = on_exit_or_evict                                                
priority = 20                                                
arguments = -t ./MarlinCalib4255.sh CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_099.xml                                                     
transfer_input_files = /scratch1/DD4hepDetCalibration/Root_File_Generation/./MarlinCalib4255.sh,/scratch0/scratch1/DD4hepDetCalibration/Xml_Generation/../Marlin_Xml/CLIC_PfoAnalysis_50_GeV_Energy_K0L_SN_099.xml,../Xml_Generation/PandoraSettingsDefault.xml,../Xml_Generation/PandoraLikelihoodData12EBin.xml,./credentials.krb5,../GearOutput.xml,/scratch0/scratch1/CalibDataForDD4hep/CLIC_o3_v14//K0L/50/ddsim_LC17-12-13_gcc7_CLIC_o3_v14_K0L50_099.slcio
queue 1
